### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by Sturmey66** [bbayles/vod_metadata#21]
appears to run, gives error saying:
_Processing index0.ts...
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python\lib\site-packages\vod_metadata\__main__.py", line 57, in <module>
    vod_package = generate_metadata(file_path, vod_config, template_path)
  File "C:\Program Files (x86)\Python\lib\site-packages\vod_metadata\md_gen.py", line 68, in generate_metadata
    vod_package.check_files()
  File "C:\Program Files (x86)\Python\lib\site-packages\vod_metadata\vodpackage.py", line 220, in check_files
    self._scan_video(ae_type, ae_path)
  File "C:\Program Files (x86)\Python\lib\site-packages\vod_metadata\vodpackage.py", line 260, in _scan_video
    mpeg_info = check_video(ae_path, self.vod_config.mediainfo_path)
  File "C:\Program Files (x86)\Python\lib\site-packages\vod_metadata\media_info.py", line 76, in check_video
    raise MediaInfoError(err_msg)
vod_metadata.media_info.MediaInfoError: Could not determine all video paramters_

=====
Doesn't work with m3u8 files, Can get it to work with mp4 if nothing else is in the folder, but doesn't add "poster" information, even when the "Poster" is named the same as the media file.

**Comment by bbayles** [comment]
Re: m3u8 files, you'll probably need to copy [this configuration file](https://github.com/bbayles/vod_metadata/blob/master/vod_metadata/vod_config.ini) and add that extension to the list on line 5.

For the poster, what's the extension / file type?
